# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20160518_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='URL',
        ),
    ]
