# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_usuarios_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteles',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='hoteles',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='hoteles',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='hoteles',
            name='nombre',
        ),
        migrations.AddField(
            model_name='hoteles',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hoteles',
            name='web',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
