# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_hoteles_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteles',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
