# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20160519_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteles',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hoteles',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hoteles',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hoteles',
            name='web',
            field=models.TextField(),
        ),
    ]
