# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_hoteles_num_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteles',
            name='num_id',
        ),
    ]
