# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_remove_hoteles_num_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteles',
            name='num_id',
            field=models.IntegerField(null=True),
        ),
    ]
