# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_hoteles_num_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.CharField(max_length=64)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.hoteles')),
            ],
        ),
    ]
