# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20160520_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
