# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_comentarios_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
