# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_comentarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='numero',
        ),
    ]
