# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_remove_comentarios_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='selecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.hoteles')),
            ],
        ),
    ]
