# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_selecciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecciones',
            name='usuario',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
