# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_auto_20160606_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, null=True)),
                ('titulo_selecciones', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='selecciones',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='selecciones',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.usuarios'),
        ),
    ]
