# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_auto_20160607_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteles',
            name='estrellas',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
