# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_auto_20160609_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='background_colour',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='letter_size',
        ),
    ]
