# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_auto_20160609_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecciones',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
